### ISSUE TITLE
Update to App

### ISSUE THREAD

**Issue by ch3ck** [silicon-mountain/smconf-android#1]
Push current work status

**Comment by ch3ck** [comment]
@Tcheutchoua-Steve @larrytech7 Any updates to this?

**Comment by Tcheutchoua-Steve** [comment]
Just pushed my current status.

**Comment by ch3ck** [comment]
Good Let me check it out @Tcheutchoua-Steve

**Comment by Tcheutchoua-Steve** [comment]
@larrytech7 could you merge the previous work you did (smconf strings, icon etc) with this repo, had difficulties doing that.
